/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.8
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = It.FattureInCloud.Sdk.Client.OpenAPIDateConverter;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// CashbookEntryInData
    /// </summary>
    [DataContract(Name = "CashbookEntryInData")]
    public partial class CashbookEntryInData : IEquatable<CashbookEntryInData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CashbookEntryInData" /> class.
        /// </summary>
        /// <param name="amountIn">Total amount in..</param>
        /// <param name="paymentAccountIn">paymentAccountIn.</param>
        public CashbookEntryInData(decimal amountIn = default(decimal), PaymentAccount paymentAccountIn = default(PaymentAccount))
        {
            this.AmountIn = amountIn;
            this.PaymentAccountIn = paymentAccountIn;
        }

        /// <summary>
        /// Total amount in.
        /// </summary>
        /// <value>Total amount in.</value>
        [DataMember(Name = "amount_in", EmitDefaultValue = false)]
        public decimal AmountIn { get; set; }

        /// <summary>
        /// Gets or Sets PaymentAccountIn
        /// </summary>
        [DataMember(Name = "payment_account_in", EmitDefaultValue = true)]
        public PaymentAccount PaymentAccountIn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CashbookEntryInData {\n");
            sb.Append("  AmountIn: ").Append(AmountIn).Append("\n");
            sb.Append("  PaymentAccountIn: ").Append(PaymentAccountIn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CashbookEntryInData);
        }

        /// <summary>
        /// Returns true if CashbookEntryInData instances are equal
        /// </summary>
        /// <param name="input">Instance of CashbookEntryInData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CashbookEntryInData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AmountIn == input.AmountIn ||
                    this.AmountIn.Equals(input.AmountIn)
                ) && 
                (
                    this.PaymentAccountIn == input.PaymentAccountIn ||
                    (this.PaymentAccountIn != null &&
                    this.PaymentAccountIn.Equals(input.PaymentAccountIn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.AmountIn.GetHashCode();
                if (this.PaymentAccountIn != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentAccountIn.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
