// <auto-generated>
/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using It.FattureInCloud.Sdk.Client;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// CreateWebhooksSubscriptionResponse
    /// </summary>
    public partial class CreateWebhooksSubscriptionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateWebhooksSubscriptionResponse" /> class.
        /// </summary>
        /// <param name="data">data</param>
        /// <param name="warnings">Webhooks registration warnings</param>
        [JsonConstructor]
        public CreateWebhooksSubscriptionResponse(Option<WebhooksSubscription> data = default, Option<List<string>> warnings = default)
        {
            DataOption = data;
            WarningsOption = warnings;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<WebhooksSubscription> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public WebhooksSubscription Data { get { return this.DataOption; } set { this.DataOption = new Option<WebhooksSubscription>(value); } }

        /// <summary>
        /// Used to track the state of Warnings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> WarningsOption { get; private set; }

        /// <summary>
        /// Webhooks registration warnings
        /// </summary>
        /// <value>Webhooks registration warnings</value>
        [JsonPropertyName("warnings")]
        public List<string> Warnings { get { return this.WarningsOption; } set { this.WarningsOption = new Option<List<string>>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateWebhooksSubscriptionResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

    }


    /// <summary>
    /// A Json converter for type <see cref="CreateWebhooksSubscriptionResponse" />
    /// </summary>
    public class CreateWebhooksSubscriptionResponseJsonConverter : JsonConverter<CreateWebhooksSubscriptionResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateWebhooksSubscriptionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateWebhooksSubscriptionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<WebhooksSubscription> data = default;
            Option<List<string>> warnings = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<WebhooksSubscription>(JsonSerializer.Deserialize<WebhooksSubscription>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "warnings":
                            warnings = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class CreateWebhooksSubscriptionResponse.");

            return new CreateWebhooksSubscriptionResponse(data, warnings);
        }

        /// <summary>
        /// Serializes a <see cref="CreateWebhooksSubscriptionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createWebhooksSubscriptionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateWebhooksSubscriptionResponse createWebhooksSubscriptionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createWebhooksSubscriptionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateWebhooksSubscriptionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createWebhooksSubscriptionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateWebhooksSubscriptionResponse createWebhooksSubscriptionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createWebhooksSubscriptionResponse.DataOption.IsSet && createWebhooksSubscriptionResponse.Data == null)
                throw new ArgumentNullException(nameof(createWebhooksSubscriptionResponse.Data), "Property is required for class CreateWebhooksSubscriptionResponse.");

            if (createWebhooksSubscriptionResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, createWebhooksSubscriptionResponse.Data, jsonSerializerOptions);
            }
            if (createWebhooksSubscriptionResponse.WarningsOption.IsSet)
                if (createWebhooksSubscriptionResponse.WarningsOption.Value != null)
                {
                    writer.WritePropertyName("warnings");
                    JsonSerializer.Serialize(writer, createWebhooksSubscriptionResponse.Warnings, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("warnings");
        }
    }
}
