// <auto-generated>
/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using It.FattureInCloud.Sdk.Client;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// GetExistingReceivedDocumentTotalsResponse
    /// </summary>
    public partial class GetExistingReceivedDocumentTotalsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetExistingReceivedDocumentTotalsResponse" /> class.
        /// </summary>
        /// <param name="data">data</param>
        [JsonConstructor]
        public GetExistingReceivedDocumentTotalsResponse(Option<ReceivedDocumentTotals> data = default)
        {
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ReceivedDocumentTotals> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public ReceivedDocumentTotals Data { get { return this.DataOption; } set { this.DataOption = new Option<ReceivedDocumentTotals>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetExistingReceivedDocumentTotalsResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

    }


    /// <summary>
    /// A Json converter for type <see cref="GetExistingReceivedDocumentTotalsResponse" />
    /// </summary>
    public class GetExistingReceivedDocumentTotalsResponseJsonConverter : JsonConverter<GetExistingReceivedDocumentTotalsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetExistingReceivedDocumentTotalsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetExistingReceivedDocumentTotalsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ReceivedDocumentTotals> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<ReceivedDocumentTotals>(JsonSerializer.Deserialize<ReceivedDocumentTotals>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class GetExistingReceivedDocumentTotalsResponse.");

            return new GetExistingReceivedDocumentTotalsResponse(data);
        }

        /// <summary>
        /// Serializes a <see cref="GetExistingReceivedDocumentTotalsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getExistingReceivedDocumentTotalsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetExistingReceivedDocumentTotalsResponse getExistingReceivedDocumentTotalsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getExistingReceivedDocumentTotalsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetExistingReceivedDocumentTotalsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getExistingReceivedDocumentTotalsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetExistingReceivedDocumentTotalsResponse getExistingReceivedDocumentTotalsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getExistingReceivedDocumentTotalsResponse.DataOption.IsSet && getExistingReceivedDocumentTotalsResponse.Data == null)
                throw new ArgumentNullException(nameof(getExistingReceivedDocumentTotalsResponse.Data), "Property is required for class GetExistingReceivedDocumentTotalsResponse.");

            if (getExistingReceivedDocumentTotalsResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, getExistingReceivedDocumentTotalsResponse.Data, jsonSerializerOptions);
            }
        }
    }
}
