// <auto-generated>
/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using It.FattureInCloud.Sdk.Client;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// GetEInvoiceRejectionReasonResponse
    /// </summary>
    public partial class GetEInvoiceRejectionReasonResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEInvoiceRejectionReasonResponse" /> class.
        /// </summary>
        /// <param name="data">data</param>
        [JsonConstructor]
        public GetEInvoiceRejectionReasonResponse(Option<EInvoiceRejectionReason> data = default)
        {
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EInvoiceRejectionReason> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public EInvoiceRejectionReason Data { get { return this.DataOption; } set { this.DataOption = new Option<EInvoiceRejectionReason>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEInvoiceRejectionReasonResponse {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

    }


    /// <summary>
    /// A Json converter for type <see cref="GetEInvoiceRejectionReasonResponse" />
    /// </summary>
    public class GetEInvoiceRejectionReasonResponseJsonConverter : JsonConverter<GetEInvoiceRejectionReasonResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetEInvoiceRejectionReasonResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetEInvoiceRejectionReasonResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EInvoiceRejectionReason> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<EInvoiceRejectionReason>(JsonSerializer.Deserialize<EInvoiceRejectionReason>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class GetEInvoiceRejectionReasonResponse.");

            return new GetEInvoiceRejectionReasonResponse(data);
        }

        /// <summary>
        /// Serializes a <see cref="GetEInvoiceRejectionReasonResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEInvoiceRejectionReasonResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetEInvoiceRejectionReasonResponse getEInvoiceRejectionReasonResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getEInvoiceRejectionReasonResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetEInvoiceRejectionReasonResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getEInvoiceRejectionReasonResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetEInvoiceRejectionReasonResponse getEInvoiceRejectionReasonResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getEInvoiceRejectionReasonResponse.DataOption.IsSet && getEInvoiceRejectionReasonResponse.Data == null)
                throw new ArgumentNullException(nameof(getEInvoiceRejectionReasonResponse.Data), "Property is required for class GetEInvoiceRejectionReasonResponse.");

            if (getEInvoiceRejectionReasonResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, getEInvoiceRejectionReasonResponse.Data, jsonSerializerOptions);
            }
        }
    }
}
