// <auto-generated>
/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.5
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using It.FattureInCloud.Sdk.Client;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// ModifyIssuedDocumentRequest
    /// </summary>
    public partial class ModifyIssuedDocumentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyIssuedDocumentRequest" /> class.
        /// </summary>
        /// <param name="data">data</param>
        /// <param name="options">options</param>
        [JsonConstructor]
        public ModifyIssuedDocumentRequest(Option<IssuedDocument> data = default, Option<IssuedDocumentOptions> options = default)
        {
            DataOption = data;
            OptionsOption = options;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssuedDocument> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public IssuedDocument Data { get { return this.DataOption; } set { this.DataOption = new Option<IssuedDocument>(value); } }

        /// <summary>
        /// Used to track the state of Options
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<IssuedDocumentOptions> OptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [JsonPropertyName("options")]
        public IssuedDocumentOptions Options { get { return this.OptionsOption; } set { this.OptionsOption = new Option<IssuedDocumentOptions>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModifyIssuedDocumentRequest {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

    }


    /// <summary>
    /// A Json converter for type <see cref="ModifyIssuedDocumentRequest" />
    /// </summary>
    public class ModifyIssuedDocumentRequestJsonConverter : JsonConverter<ModifyIssuedDocumentRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ModifyIssuedDocumentRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ModifyIssuedDocumentRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<IssuedDocument> data = default;
            Option<IssuedDocumentOptions> options = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "data":
                            data = new Option<IssuedDocument>(JsonSerializer.Deserialize<IssuedDocument>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "options":
                            options = new Option<IssuedDocumentOptions>(JsonSerializer.Deserialize<IssuedDocumentOptions>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class ModifyIssuedDocumentRequest.");

            if (options.IsSet && options.Value == null)
                throw new ArgumentNullException(nameof(options), "Property is not nullable for class ModifyIssuedDocumentRequest.");

            return new ModifyIssuedDocumentRequest(data, options);
        }

        /// <summary>
        /// Serializes a <see cref="ModifyIssuedDocumentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="modifyIssuedDocumentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ModifyIssuedDocumentRequest modifyIssuedDocumentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, modifyIssuedDocumentRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ModifyIssuedDocumentRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="modifyIssuedDocumentRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ModifyIssuedDocumentRequest modifyIssuedDocumentRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (modifyIssuedDocumentRequest.DataOption.IsSet && modifyIssuedDocumentRequest.Data == null)
                throw new ArgumentNullException(nameof(modifyIssuedDocumentRequest.Data), "Property is required for class ModifyIssuedDocumentRequest.");

            if (modifyIssuedDocumentRequest.OptionsOption.IsSet && modifyIssuedDocumentRequest.Options == null)
                throw new ArgumentNullException(nameof(modifyIssuedDocumentRequest.Options), "Property is required for class ModifyIssuedDocumentRequest.");

            if (modifyIssuedDocumentRequest.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, modifyIssuedDocumentRequest.Data, jsonSerializerOptions);
            }
            if (modifyIssuedDocumentRequest.OptionsOption.IsSet)
            {
                writer.WritePropertyName("options");
                JsonSerializer.Serialize(writer, modifyIssuedDocumentRequest.Options, jsonSerializerOptions);
            }
        }
    }
}
