/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = It.FattureInCloud.Sdk.Client.OpenAPIDateConverter;

namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    /// PendingReceivedDocumentExtractedDataMining
    /// </summary>
    [DataContract(Name = "PendingReceivedDocument_extracted_data_mining")]
    public partial class PendingReceivedDocumentExtractedDataMining : IEquatable<PendingReceivedDocumentExtractedDataMining>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PendingReceivedDocumentExtractedDataMining" /> class.
        /// </summary>
        /// <param name="saveEntity">saveEntity.</param>
        public PendingReceivedDocumentExtractedDataMining(bool saveEntity = default)
        {
            this._SaveEntity = saveEntity;
            if (this.SaveEntity != null)
            {
                this._flagSaveEntity = true;
            }
        }

        /// <summary>
        /// Gets or Sets SaveEntity
        /// </summary>
        [DataMember(Name = "save_entity", EmitDefaultValue = true)]
        public bool SaveEntity
        {
            get { return _SaveEntity; }
            set
            {
                _SaveEntity = value;
                _flagSaveEntity = true;
            }
        }
        private bool _SaveEntity;
        private bool _flagSaveEntity;

        /// <summary>
        /// Returns false as SaveEntity should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSaveEntity()
        {
            return _flagSaveEntity;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PendingReceivedDocumentExtractedDataMining {\n");
            sb.Append("  SaveEntity: ").Append(SaveEntity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PendingReceivedDocumentExtractedDataMining);
        }

        /// <summary>
        /// Returns true if PendingReceivedDocumentExtractedDataMining instances are equal
        /// </summary>
        /// <param name="input">Instance of PendingReceivedDocumentExtractedDataMining to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PendingReceivedDocumentExtractedDataMining input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.SaveEntity == input.SaveEntity ||
                    this.SaveEntity.Equals(input.SaveEntity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.SaveEntity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
