/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.16
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    ///     Default values for the document items.
    /// </summary>
    [DataContract(Name = "ReceivedDocumentInfo_items_default_values")]
    public class ReceivedDocumentInfoItemsDefaultValues : IEquatable<ReceivedDocumentInfoItemsDefaultValues>,
        IValidatableObject
    {
        private bool _flagVat;
        private decimal? _Vat;

        /// <summary>
        ///     Initializes a new instance of the <see cref="ReceivedDocumentInfoItemsDefaultValues" /> class.
        /// </summary>
        /// <param name="vat">Default vat value..</param>
        public ReceivedDocumentInfoItemsDefaultValues(decimal? vat = default(decimal?))
        {
            _Vat = vat;
            if (Vat != null) _flagVat = true;
        }

        /// <summary>
        ///     Default vat value.
        /// </summary>
        /// <value>Default vat value.</value>
        [DataMember(Name = "vat", EmitDefaultValue = true)]
        public decimal? Vat
        {
            get => _Vat;
            set
            {
                _Vat = value;
                _flagVat = true;
            }
        }

        /// <summary>
        ///     Returns false as Vat should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeVat()
        {
            return _flagVat;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReceivedDocumentInfoItemsDefaultValues {\n");
            sb.Append("  Vat: ").Append(Vat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as ReceivedDocumentInfoItemsDefaultValues);
        }

        /// <summary>
        ///     Returns true if ReceivedDocumentInfoItemsDefaultValues instances are equal
        /// </summary>
        /// <param name="input">Instance of ReceivedDocumentInfoItemsDefaultValues to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReceivedDocumentInfoItemsDefaultValues input)
        {
            if (input == null) return false;
            return
                Vat == input.Vat ||
                (Vat != null &&
                 Vat.Equals(input.Vat));
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Vat != null) hashCode = hashCode * 59 + Vat.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(
            ValidationContext validationContext)
        {
            yield break;
        }
    }
}