/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.16
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace It.FattureInCloud.Sdk.Model
{
    /// <summary>
    ///     VatType
    /// </summary>
    [DataContract(Name = "VatType")]
    public class VatType : IEquatable<VatType>, IValidatableObject
    {
        private string _Description;
        private string _EiDescription;
        private bool? _EInvoice;
        private string _EiType;
        private bool _flagDescription;
        private bool _flagEiDescription;
        private bool _flagEInvoice;
        private bool _flagEiType;
        private bool _flagId;
        private bool _flagIsDisabled;
        private bool _flagNotes;
        private bool _flagValue;
        private int? _Id;
        private bool? _IsDisabled;
        private string _Notes;
        private decimal? _Value;

        /// <summary>
        ///     Initializes a new instance of the <see cref="VatType" /> class.
        /// </summary>
        /// <param name="id">Unique identifier.</param>
        /// <param name="value">[Read Only] Percentual value..</param>
        /// <param name="description">Short description..</param>
        /// <param name="notes">Long description and notes shown in documents..</param>
        /// <param name="eInvoice">Usable for e-invoices..</param>
        /// <param name="eiType">E-invoice type (natura)..</param>
        /// <param name="eiDescription">E-invoice description..</param>
        /// <param name="isDisabled">Determine if the vat type is disabled..</param>
        public VatType(int? id = default(int?), decimal? value = default(decimal?),
            string description = default(string), string notes = default(string), bool? eInvoice = default(bool?),
            string eiType = default(string), string eiDescription = default(string), bool? isDisabled = default(bool?))
        {
            _Id = id;
            if (Id != null) _flagId = true;
            _Value = value;
            if (Value != null) _flagValue = true;
            _Description = description;
            if (Description != null) _flagDescription = true;
            _Notes = notes;
            if (Notes != null) _flagNotes = true;
            _EInvoice = eInvoice;
            if (EInvoice != null) _flagEInvoice = true;
            _EiType = eiType;
            if (EiType != null) _flagEiType = true;
            _EiDescription = eiDescription;
            if (EiDescription != null) _flagEiDescription = true;
            _IsDisabled = isDisabled;
            if (IsDisabled != null) _flagIsDisabled = true;
        }

        /// <summary>
        ///     Unique identifier
        /// </summary>
        /// <value>Unique identifier</value>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public int? Id
        {
            get => _Id;
            set
            {
                _Id = value;
                _flagId = true;
            }
        }

        /// <summary>
        ///     [Read Only] Percentual value.
        /// </summary>
        /// <value>[Read Only] Percentual value.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        public decimal? Value
        {
            get => _Value;
            set
            {
                _Value = value;
                _flagValue = true;
            }
        }

        /// <summary>
        ///     Short description.
        /// </summary>
        /// <value>Short description.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description
        {
            get => _Description;
            set
            {
                _Description = value;
                _flagDescription = true;
            }
        }

        /// <summary>
        ///     Long description and notes shown in documents.
        /// </summary>
        /// <value>Long description and notes shown in documents.</value>
        [DataMember(Name = "notes", EmitDefaultValue = true)]
        public string Notes
        {
            get => _Notes;
            set
            {
                _Notes = value;
                _flagNotes = true;
            }
        }

        /// <summary>
        ///     Usable for e-invoices.
        /// </summary>
        /// <value>Usable for e-invoices.</value>
        [DataMember(Name = "e_invoice", EmitDefaultValue = true)]
        public bool? EInvoice
        {
            get => _EInvoice;
            set
            {
                _EInvoice = value;
                _flagEInvoice = true;
            }
        }

        /// <summary>
        ///     E-invoice type (natura).
        /// </summary>
        /// <value>E-invoice type (natura).</value>
        [DataMember(Name = "ei_type", EmitDefaultValue = true)]
        public string EiType
        {
            get => _EiType;
            set
            {
                _EiType = value;
                _flagEiType = true;
            }
        }

        /// <summary>
        ///     E-invoice description.
        /// </summary>
        /// <value>E-invoice description.</value>
        [DataMember(Name = "ei_description", EmitDefaultValue = true)]
        public string EiDescription
        {
            get => _EiDescription;
            set
            {
                _EiDescription = value;
                _flagEiDescription = true;
            }
        }

        /// <summary>
        ///     [Read Only] Determine if this vat type is editable.
        /// </summary>
        /// <value>[Read Only] Determine if this vat type is editable.</value>
        [DataMember(Name = "editable", EmitDefaultValue = true)]
        public bool? Editable { get; private set; }

        /// <summary>
        ///     Determine if the vat type is disabled.
        /// </summary>
        /// <value>Determine if the vat type is disabled.</value>
        [DataMember(Name = "is_disabled", EmitDefaultValue = true)]
        public bool? IsDisabled
        {
            get => _IsDisabled;
            set
            {
                _IsDisabled = value;
                _flagIsDisabled = true;
            }
        }

        /// <summary>
        ///     Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }

        /// <summary>
        ///     Returns false as Value should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeValue()
        {
            return _flagValue;
        }

        /// <summary>
        ///     Returns false as Description should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDescription()
        {
            return _flagDescription;
        }

        /// <summary>
        ///     Returns false as Notes should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNotes()
        {
            return _flagNotes;
        }

        /// <summary>
        ///     Returns false as EInvoice should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEInvoice()
        {
            return _flagEInvoice;
        }

        /// <summary>
        ///     Returns false as EiType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEiType()
        {
            return _flagEiType;
        }

        /// <summary>
        ///     Returns false as EiDescription should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEiDescription()
        {
            return _flagEiDescription;
        }

        /// <summary>
        ///     Returns false as Editable should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEditable()
        {
            return false;
        }

        /// <summary>
        ///     Returns false as IsDisabled should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIsDisabled()
        {
            return _flagIsDisabled;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VatType {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  EInvoice: ").Append(EInvoice).Append("\n");
            sb.Append("  EiType: ").Append(EiType).Append("\n");
            sb.Append("  EiDescription: ").Append(EiDescription).Append("\n");
            sb.Append("  Editable: ").Append(Editable).Append("\n");
            sb.Append("  IsDisabled: ").Append(IsDisabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        ///     Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as VatType);
        }

        /// <summary>
        ///     Returns true if VatType instances are equal
        /// </summary>
        /// <param name="input">Instance of VatType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VatType input)
        {
            if (input == null) return false;
            return
                (
                    Id == input.Id ||
                    (Id != null &&
                     Id.Equals(input.Id))
                ) &&
                (
                    Value == input.Value ||
                    (Value != null &&
                     Value.Equals(input.Value))
                ) &&
                (
                    Description == input.Description ||
                    (Description != null &&
                     Description.Equals(input.Description))
                ) &&
                (
                    Notes == input.Notes ||
                    (Notes != null &&
                     Notes.Equals(input.Notes))
                ) &&
                (
                    EInvoice == input.EInvoice ||
                    (EInvoice != null &&
                     EInvoice.Equals(input.EInvoice))
                ) &&
                (
                    EiType == input.EiType ||
                    (EiType != null &&
                     EiType.Equals(input.EiType))
                ) &&
                (
                    EiDescription == input.EiDescription ||
                    (EiDescription != null &&
                     EiDescription.Equals(input.EiDescription))
                ) &&
                (
                    Editable == input.Editable ||
                    (Editable != null &&
                     Editable.Equals(input.Editable))
                ) &&
                (
                    IsDisabled == input.IsDisabled ||
                    (IsDisabled != null &&
                     IsDisabled.Equals(input.IsDisabled))
                );
        }

        /// <summary>
        ///     Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (Id != null) hashCode = hashCode * 59 + Id.GetHashCode();
                if (Value != null) hashCode = hashCode * 59 + Value.GetHashCode();
                if (Description != null) hashCode = hashCode * 59 + Description.GetHashCode();
                if (Notes != null) hashCode = hashCode * 59 + Notes.GetHashCode();
                if (EInvoice != null) hashCode = hashCode * 59 + EInvoice.GetHashCode();
                if (EiType != null) hashCode = hashCode * 59 + EiType.GetHashCode();
                if (EiDescription != null) hashCode = hashCode * 59 + EiDescription.GetHashCode();
                if (Editable != null) hashCode = hashCode * 59 + Editable.GetHashCode();
                if (IsDisabled != null) hashCode = hashCode * 59 + IsDisabled.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        ///     To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(
            ValidationContext validationContext)
        {
            yield break;
        }
    }
}