/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CashbookEntryInData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CashbookEntryInDataTests : IDisposable
    {
        private CashbookEntryInData instance;

        public CashbookEntryInDataTests()
        {
            var body = "{ 'amount_in': 12345, 'payment_account_in': { 'id': 333 } }";
            instance = JsonConvert.DeserializeObject<CashbookEntryInData>(body);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CashbookEntryInData
        /// </summary>
        [Fact]
        public void CashbookEntryInDataInstanceTest()
        {
            Assert.IsType<CashbookEntryInData>(instance);
        }


        /// <summary>
        /// Test the property 'AmountIn'
        /// </summary>
        [Fact]
        public void AmountInTest()
        {
            Assert.IsType<decimal>(instance.AmountIn);
        }
        /// <summary>
        /// Test the property 'PaymentAccountIn'
        /// </summary>
        [Fact]
        public void PaymentAccountInTest()
        {
            Assert.IsType<PaymentAccount>(instance.PaymentAccountIn);
        }

    }

}
