/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.14
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DetailedCountry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DetailedCountryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DetailedCountry
        //private DetailedCountry instance;

        public DetailedCountryTests()
        {
            // TODO uncomment below to create an instance of DetailedCountry
            //instance = new DetailedCountry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DetailedCountry
        /// </summary>
        [Fact]
        public void DetailedCountryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DetailedCountry
            //Assert.IsType<DetailedCountry>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SettingsName'
        /// </summary>
        [Fact]
        public void SettingsNameTest()
        {
            // TODO unit test for the property 'SettingsName'
        }
        /// <summary>
        /// Test the property 'Iso'
        /// </summary>
        [Fact]
        public void IsoTest()
        {
            // TODO unit test for the property 'Iso'
        }
        /// <summary>
        /// Test the property 'FiscalIso'
        /// </summary>
        [Fact]
        public void FiscalIsoTest()
        {
            // TODO unit test for the property 'FiscalIso'
        }
        /// <summary>
        /// Test the property 'Uic'
        /// </summary>
        [Fact]
        public void UicTest()
        {
            // TODO unit test for the property 'Uic'
        }

    }

}
