/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.11
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EinvoiceRejectionReason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EinvoiceRejectionReasonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EinvoiceRejectionReason
        //private EinvoiceRejectionReason instance;

        public EinvoiceRejectionReasonTests()
        {
            // TODO uncomment below to create an instance of EinvoiceRejectionReason
            //instance = new EinvoiceRejectionReason();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EinvoiceRejectionReason
        /// </summary>
        [Fact]
        public void EinvoiceRejectionReasonInstanceTest()
        {
            // TODO uncomment below to test "IsType" EinvoiceRejectionReason
            //Assert.IsType<EinvoiceRejectionReason>(instance);
        }


        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'EiStatus'
        /// </summary>
        [Fact]
        public void EiStatusTest()
        {
            // TODO unit test for the property 'EiStatus'
        }
        /// <summary>
        /// Test the property 'Solution'
        /// </summary>
        [Fact]
        public void SolutionTest()
        {
            // TODO unit test for the property 'Solution'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }

    }

}
