/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.22
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Email
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Email
        //private Email instance;

        public EmailTests()
        {
            // TODO uncomment below to create an instance of Email
            //instance = new Email();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Email
        /// </summary>
        [Fact]
        public void EmailInstanceTest()
        {
            // TODO uncomment below to test "IsType" Email
            //Assert.IsType<Email>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SentDate'
        /// </summary>
        [Fact]
        public void SentDateTest()
        {
            // TODO unit test for the property 'SentDate'
        }
        /// <summary>
        /// Test the property 'ErrorsCount'
        /// </summary>
        [Fact]
        public void ErrorsCountTest()
        {
            // TODO unit test for the property 'ErrorsCount'
        }
        /// <summary>
        /// Test the property 'ErrorLog'
        /// </summary>
        [Fact]
        public void ErrorLogTest()
        {
            // TODO unit test for the property 'ErrorLog'
        }
        /// <summary>
        /// Test the property 'FromEmail'
        /// </summary>
        [Fact]
        public void FromEmailTest()
        {
            // TODO unit test for the property 'FromEmail'
        }
        /// <summary>
        /// Test the property 'FromName'
        /// </summary>
        [Fact]
        public void FromNameTest()
        {
            // TODO unit test for the property 'FromName'
        }
        /// <summary>
        /// Test the property 'ToEmail'
        /// </summary>
        [Fact]
        public void ToEmailTest()
        {
            // TODO unit test for the property 'ToEmail'
        }
        /// <summary>
        /// Test the property 'ToName'
        /// </summary>
        [Fact]
        public void ToNameTest()
        {
            // TODO unit test for the property 'ToName'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'CopyTo'
        /// </summary>
        [Fact]
        public void CopyToTest()
        {
            // TODO unit test for the property 'CopyTo'
        }
        /// <summary>
        /// Test the property 'RecipientStatus'
        /// </summary>
        [Fact]
        public void RecipientStatusTest()
        {
            // TODO unit test for the property 'RecipientStatus'
        }
        /// <summary>
        /// Test the property 'RecipientDate'
        /// </summary>
        [Fact]
        public void RecipientDateTest()
        {
            // TODO unit test for the property 'RecipientDate'
        }
        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }
        /// <summary>
        /// Test the property 'Attachments'
        /// </summary>
        [Fact]
        public void AttachmentsTest()
        {
            // TODO unit test for the property 'Attachments'
        }

    }

}
