/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing IssuedDocumentPreCreateInfoExtraDataDefaultValues
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssuedDocumentPreCreateInfoExtraDataDefaultValuesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssuedDocumentPreCreateInfoExtraDataDefaultValues
        //private IssuedDocumentPreCreateInfoExtraDataDefaultValues instance;

        public IssuedDocumentPreCreateInfoExtraDataDefaultValuesTests()
        {
            // TODO uncomment below to create an instance of IssuedDocumentPreCreateInfoExtraDataDefaultValues
            //instance = new IssuedDocumentPreCreateInfoExtraDataDefaultValues();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssuedDocumentPreCreateInfoExtraDataDefaultValues
        /// </summary>
        [Fact]
        public void IssuedDocumentPreCreateInfoExtraDataDefaultValuesInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssuedDocumentPreCreateInfoExtraDataDefaultValues
            //Assert.IsType<IssuedDocumentPreCreateInfoExtraDataDefaultValues>(instance);
        }


        /// <summary>
        /// Test the property 'TsCommunication'
        /// </summary>
        [Fact]
        public void TsCommunicationTest()
        {
            // TODO unit test for the property 'TsCommunication'
        }
        /// <summary>
        /// Test the property 'TsTipoSpesa'
        /// </summary>
        [Fact]
        public void TsTipoSpesaTest()
        {
            // TODO unit test for the property 'TsTipoSpesa'
        }
        /// <summary>
        /// Test the property 'TsFlagTipoSpesa'
        /// </summary>
        [Fact]
        public void TsFlagTipoSpesaTest()
        {
            // TODO unit test for the property 'TsFlagTipoSpesa'
        }
        /// <summary>
        /// Test the property 'TsPagamentoTracciato'
        /// </summary>
        [Fact]
        public void TsPagamentoTracciatoTest()
        {
            // TODO unit test for the property 'TsPagamentoTracciato'
        }

    }

}
