/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol. For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.2
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ReceiptPreCreateInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReceiptPreCreateInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReceiptPreCreateInfo
        //private ReceiptPreCreateInfo instance;

        public ReceiptPreCreateInfoTests()
        {
            // TODO uncomment below to create an instance of ReceiptPreCreateInfo
            //instance = new ReceiptPreCreateInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReceiptPreCreateInfo
        /// </summary>
        [Fact]
        public void ReceiptPreCreateInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReceiptPreCreateInfo
            //Assert.IsType<ReceiptPreCreateInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Numerations'
        /// </summary>
        [Fact]
        public void NumerationsTest()
        {
            // TODO unit test for the property 'Numerations'
        }
        /// <summary>
        /// Test the property 'NumerationsList'
        /// </summary>
        [Fact]
        public void NumerationsListTest()
        {
            // TODO unit test for the property 'NumerationsList'
        }
        /// <summary>
        /// Test the property 'RcCentersList'
        /// </summary>
        [Fact]
        public void RcCentersListTest()
        {
            // TODO unit test for the property 'RcCentersList'
        }
        /// <summary>
        /// Test the property 'PaymentAccountsList'
        /// </summary>
        [Fact]
        public void PaymentAccountsListTest()
        {
            // TODO unit test for the property 'PaymentAccountsList'
        }
        /// <summary>
        /// Test the property 'CategoriesList'
        /// </summary>
        [Fact]
        public void CategoriesListTest()
        {
            // TODO unit test for the property 'CategoriesList'
        }
        /// <summary>
        /// Test the property 'VatTypesList'
        /// </summary>
        [Fact]
        public void VatTypesListTest()
        {
            // TODO unit test for the property 'VatTypesList'
        }

    }

}
