/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 400.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.  For more information, please visit https://www.fattureincloud.it.
 *
 * The version of the OpenAPI document: 2.0.3
 * Contact: info@fattureincloud.it
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using It.FattureInCloud.Sdk.Api;
using It.FattureInCloud.Sdk.Model;
using It.FattureInCloud.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace It.FattureInCloud.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyEInvoiceXmlResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyEInvoiceXmlResponseTests : IDisposable
    {
        private VerifyEInvoiceXmlResponse instance;
        private VerifyEInvoiceXmlResponse instance_err;

        public VerifyEInvoiceXmlResponseTests()
        {
            var body = "{ 'data': { 'success': true } }";
            var body_err = "{ 'error': { 'message': 'errore', 'validation_result': { 'success': false } }, 'extra': { 'errors': [ 'errore brutto' ] } }";
            instance = JsonConvert.DeserializeObject<VerifyEInvoiceXmlResponse>(body);
            instance_err = JsonConvert.DeserializeObject<VerifyEInvoiceXmlResponse>(body_err);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyEInvoiceXmlResponse
        /// </summary>
        [Fact]
        public void VerifyEInvoiceXmlResponseInstanceTest()
        {
            Assert.IsType<VerifyEInvoiceXmlResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            Assert.IsType<VerifyEInvoiceXmlSuccessResponseData>(instance.GetVerifyEInvoiceXmlSuccessResponse().Data);
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            Assert.IsType<VerifyEInvoiceXmlErrorResponseError>(instance_err.GetVerifyEInvoiceXmlErrorResponse().Error);
        }
        /// <summary>
        /// Test the property 'Extra'
        /// </summary>
        [Fact]
        public void ExtraTest()
        {
            Assert.IsType<VerifyEInvoiceXmlErrorResponseExtra>(instance_err.GetVerifyEInvoiceXmlErrorResponse().Extra);
        }

    }

}
