name: C# SDK Validation

on:
  pull_request:
    branches: [master]
jobs:
  validate:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # dotnet: [ '3.1.x', '5.0.x' ]
    #     dotnet: [ '3.1.x' ]

    name: Dotnet validation

    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v4

      - id: setup-dotnet
        name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x

      - id: clean
        name: Clean
        run: dotnet clean

      - id: restore
        name: Restore dependencies
        run: dotnet restore

      - id: build
        name: Build
        run: dotnet build --no-restore --configuration=Release

      - id: test
        name: Test
        run: dotnet test --no-build --verbosity normal --configuration=Release
