name: C# SDK Validation

on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
        
    name: Dotnet ${{ matrix.dotnet }} valiation
    
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v2
      
      - id: setup
        name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - id: restore
        name: Restore dependencies
        run: dotnet restore
        
      - id: build 
        name: Build
        run: dotnet build --no-restore
        
      - id: test
        name: Test
        run: dotnet test --no-build --verbosity normal
